### ISSUE TITLE
Voronoi Threshold Labler not starting

### ISSUE THREAD

**Issue by giocard** [biovoxxel/bv3dbox#3]
I cannot launch the command.
I activated the following update sites: _Biovoxxel_, _Biovoxxel 3D Box_, _clij_, _clij2_
When I start, from the _Plugins_ Menu, the command _Voronoi Threshold Labler (2D/3D)_, I get the following error:
```
(Fiji Is Just) ImageJ 2.9.0/1.53t; Java 1.8.0_172 [64-bit]; Windows 10 10.0; 1159MB of 97044MB (1%)
 
java.lang.NoClassDefFoundError: net/haesleinhuepf/clijx/imagej2/ImageJ2Tubeness
	at de.biovoxxel.bv3dbox.plugins.BV_VoronoiThresholdLabeling.<init>(BV_VoronoiThresholdLabeling.java:81)
	at de.biovoxxel.bv3dbox.gui.BV_VoronoiThresholdLabelingGUI.<init>(BV_VoronoiThresholdLabelingGUI.java:118)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.scijava.command.CommandInfo.createModule(CommandInfo.java:312)
	at org.scijava.module.DefaultModuleService.createModule(DefaultModuleService.java:167)
	at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:206)
	at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:197)
	at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:182)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:303)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.haesleinhuepf.clijx.imagej2.ImageJ2Tubeness
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more
```

**Comment by biovoxxel** [comment]
Hi @giocard,

try to also activate the 2 clijx updte sites (clijx-assistent and clijx-assistent-extensions). This should solve the issue

**Comment by giocard** [comment]
Yes, it does. Somehow I missed these requirements. Thanks!
